create table members (
  uid mediumint(8) unsigned not null auto_increment,
  username char(15) not null default '',
  password char(32) not null default '',
  secques char(8) not null default '',
  gender tinyint(1) not null default '0',
  adminid tinyint(1) not null default '0',
  groupid smallint(6) unsigned not null default '0',
  groupexpiry int(10) unsigned not null default '0',
  extgroupids char(60) not null default '',
  regip char(15) not null default '',
  regdate int(10) unsigned not null default '0',
  lastip char(15) not null default '',
  lastvisit int(10) unsigned not null default '0',
  lastactivity int(10) unsigned not null default '0',
  lastpost int(10) unsigned not null default '0',
  posts mediumint(8) unsigned not null default '0',
  digestposts smallint(6) unsigned not null default '0',
  oltime smallint(6) unsigned not null default '0',
  pageviews mediumint(8) unsigned not null default '0',
  credits int(10) not null default '0',
  extcredits1 int(10) not null default '0',
  extcredits2 int(10) not null default '0',
  extcredits3 int(10) not null default '0',
  extcredits4 int(10) not null default '0',
  extcredits5 int(10) not null default '0',
  extcredits6 int(10) not null default '0',
  extcredits7 int(10) not null default '0',
  extcredits8 int(10) not null default '0',
  email char(50) not null default '',
  bday date not null default '0000-00-00',
  sigstatus tinyint(1) not null default '0',
  tpp tinyint(3) unsigned not null default '0',
  ppp tinyint(3) unsigned not null default '0',
  styleid smallint(6) unsigned not null default '0',
  dateformat char(10) not null default '',
  timeformat tinyint(1) not null default '0',
  pmsound tinyint(1) not null default '0',
  showemail tinyint(1) not null default '0',
  newsletter tinyint(1) not null default '0',
  invisible tinyint(1) not null default '0',
  timeoffset char(4) not null default '',
  newpm tinyint(1) not null default '0',
  accessmasks tinyint(1) not null default '0',
  editormode tinyint(1) unsigned not null default '2',
  customshow tinyint(1) unsigned not null default '26',
  xspacestatus tinyint(1) not null default '0',
  primary key  (uid),
  unique key username (username),
  key email (email)
) engine=myisam default charset=utf8;


INSERT INTO `members` VALUES ('1', 'admin', 'e10adc3949ba59abbe56e057f20f883e', '', '0', '0', '0', '0', '', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'longben@163.com', '1978-05-04', '0', '0', '0', '0', '', '0', '0', '1', '0', '0', '', '0', '0', '0', '0', '0');